#!/usr/bin/env python3
"""Embed admin-ui/public/branding/logo.svg into docs/assets/logo-readme.svg with a white background (GitHub README)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOGO = ROOT / "admin-ui/public/branding/logo.svg"
OUT = ROOT / "docs/assets/logo-readme.svg"


def main() -> None:
    logo = LOGO.read_text(encoding="utf-8")
    m = re.match(r"<\?xml[^>]*\?>\s*<svg[^>]*>(.*)</svg>\s*$", logo, re.DOTALL)
    if not m:
        raise SystemExit(f"Unexpected format: {LOGO}")
    inner = m.group(1).strip()
    wrapped = f"""<svg xmlns="http://www.w3.org/2000/svg" width="960" height="300" viewBox="0 0 960 300">
  <!-- Regenerated by scripts/sync_readme_logo.py — white rect for GitHub README (HTML styles are stripped). -->
  <rect width="960" height="300" fill="#ffffff"/>
  <svg x="40" y="24" width="880" height="252" viewBox="2515.4265 1743.4298 1605.144 513.1404" preserveAspectRatio="xMidYMid meet">
{inner}
  </svg>
</svg>
"""
    OUT.write_text(wrapped, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
