#!/usr/bin/env python3
"""Embed admin-ui/public/branding/symbol.svg into docs/assets/logo-readme.svg with a white background (GitHub README)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "admin-ui/public/branding/symbol.svg"
OUT = ROOT / "docs/assets/logo-readme.svg"

README_CARD_R = 12.0


def rounded_card_path(w: float, h: float, r: float) -> str:
    r = min(r, w / 2, h / 2)

    def n(x: float) -> str:
        return str(int(x)) if float(x).is_integer() else str(x)

    wr, hr, rr = n(w), n(h), n(r)
    return (
        f"M {rr},0 H {n(w - r)} A {rr},{rr} 0 0 1 {wr},{rr} V {n(h - r)} A {rr},{rr} 0 0 1 {n(w - r)},{hr} "
        f"H {rr} A {rr},{rr} 0 0 1 0,{n(h - r)} V {rr} A {rr},{rr} 0 0 1 {rr},0 Z"
    )


def parse_viewbox(svg_text: str) -> tuple[float, float, float, float]:
    m = re.search(r"<svg[^>]*\bviewBox=\"([^\"]+)\"", svg_text)
    if not m:
        raise SystemExit(f"No viewBox on root <svg>: {SOURCE}")
    parts = [float(x) for x in m.group(1).replace(",", " ").split()]
    if len(parts) != 4:
        raise SystemExit(f"Bad viewBox {m.group(1)!r} in {SOURCE}")
    return parts[0], parts[1], parts[2], parts[3]


def main() -> None:
    raw = SOURCE.read_text(encoding="utf-8")
    m = re.match(r"<\?xml[^>]*\?>\s*<svg[^>]*>(.*)</svg>\s*$", raw, re.DOTALL)
    if not m:
        raise SystemExit(f"Unexpected format: {SOURCE}")
    inner = m.group(1).strip()
    _minx, _miny, vb_w, vb_h = parse_viewbox(raw)
    aspect = vb_w / vb_h if vb_h else 1.0
    if 0.88 <= aspect <= 1.12:
        card_w = card_h = 400.0
        pad = 36.0
        slot = card_w - 2 * pad
        ix, iy = pad, pad
        iw = ih = slot
    else:
        card_w, card_h = 960.0, 300.0
        ix, iy, iw, ih = 40.0, 24.0, 880.0, 252.0

    vb_s = f"{_minx} {_miny} {vb_w} {vb_h}"
    bg = rounded_card_path(card_w, card_h, README_CARD_R)
    wrapped = f"""<svg xmlns="http://www.w3.org/2000/svg" width="{int(card_w)}" height="{int(card_h)}" viewBox="0 0 {int(card_w)} {int(card_h)}">
  <!-- Regenerated by scripts/sync_readme_logo.py from symbol.svg — rounded card via path + clip (GitHub may strip rect rx/ry). -->
  <defs>
    <clipPath id="orb-readme-card-clip"><path d="{bg}"/></clipPath>
  </defs>
  <g clip-path="url(#orb-readme-card-clip)">
    <path fill="#ffffff" d="{bg}"/>
    <svg x="{ix}" y="{iy}" width="{iw}" height="{ih}" viewBox="{vb_s}" preserveAspectRatio="xMidYMid meet">
{inner}
    </svg>
  </g>
</svg>
"""
    OUT.write_text(wrapped, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
