#!/usr/bin/env python3
"""Embed admin-ui/public/branding/logo.svg into docs/assets/logo-readme.svg with a white background (GitHub README)."""
from __future__ import annotations

import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
LOGO = ROOT / "admin-ui/public/branding/logo.svg"
OUT = ROOT / "docs/assets/logo-readme.svg"

# GitHub’s SVG sanitizer often drops rx/ry on <rect>; a filled <path> keeps 12px corners.
README_CARD_W = 960.0
README_CARD_H = 300.0
README_CARD_R = 12.0


def rounded_card_path(w: float, h: float, r: float) -> str:
    r = min(r, w / 2, h / 2)
    # Integer coordinates where possible (smaller SVG; same shape).
    def n(x: float) -> str:
        return str(int(x)) if float(x).is_integer() else str(x)

    wr, hr, rr = n(w), n(h), n(r)
    return (
        f"M {rr},0 H {n(w - r)} A {rr},{rr} 0 0 1 {wr},{rr} V {n(h - r)} A {rr},{rr} 0 0 1 {n(w - r)},{hr} "
        f"H {rr} A {rr},{rr} 0 0 1 0,{n(h - r)} V {rr} A {rr},{rr} 0 0 1 {rr},0 Z"
    )


def main() -> None:
    logo = LOGO.read_text(encoding="utf-8")
    m = re.match(r"<\?xml[^>]*\?>\s*<svg[^>]*>(.*)</svg>\s*$", logo, re.DOTALL)
    if not m:
        raise SystemExit(f"Unexpected format: {LOGO}")
    inner = m.group(1).strip()
    bg = rounded_card_path(README_CARD_W, README_CARD_H, README_CARD_R)
    wrapped = f"""<svg xmlns="http://www.w3.org/2000/svg" width="960" height="300" viewBox="0 0 960 300">
  <!-- Regenerated by scripts/sync_readme_logo.py — rounded card via path + clip (GitHub may strip rect rx/ry). -->
  <defs>
    <clipPath id="orb-readme-card-clip"><path d="{bg}"/></clipPath>
  </defs>
  <g clip-path="url(#orb-readme-card-clip)">
    <path fill="#ffffff" d="{bg}"/>
    <svg x="40" y="24" width="880" height="252" viewBox="2515.4265 1743.4298 1605.144 513.1404" preserveAspectRatio="xMidYMid meet">
{inner}
    </svg>
  </g>
</svg>
"""
    OUT.write_text(wrapped, encoding="utf-8")
    print(f"Wrote {OUT.relative_to(ROOT)} ({OUT.stat().st_size} bytes)")


if __name__ == "__main__":
    main()
